import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import LayoutWrapper from "@/components/layout-wrapper";
import { ReactFlowProvider } from "@xyflow/react";
import { Toaster } from "sonner";

const geistSans = Geist({
    variable: "--font-geist-sans",
    subsets: ["latin"],
});

const geistMono = Geist_Mono({
    variable: "--font-geist-mono",
    subsets: ["latin"],
});

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
            <ReactFlowProvider>
                <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
                    <LayoutWrapper>
                        {children}
                    </LayoutWrapper>
                    <Toaster richColors position="top-right" />
                </body>
            </ReactFlowProvider>
        </html>
    );
}
